spring:
  application.name: service-turbine
server:
  port: 9009
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: cloud-producer, cloud-consumer
  clusterNameExpression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

management:
  security:
    enabled: false
